Django/ojo/homepage/urls.py
<<<<<<< HEAD
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.home, name='home'),
    path('register/', views.register, name='register'),

    path('regcon/', views.regcon, name='regcon'),
    path('logcon/', views.logcon, name='logcon'),

    path('login/', views.login, name='login'),
    path('theme/', views.showTheme, name='theme'),
    path('<str:theme>/stay/', views.stayFilter, name='stay'),
    path('<str:name>detail/', views.stayDetail, name='staydetail'),
=======
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.home, name='home'),
    path('register/', views.register, name='register'),

    path('regcon/', views.regcon, name='regcon'),
    path('logcon/', views.logcon, name='logcon'),
    path('choice/', views.choice, name ='choice'),
    path('totalstay/', views.totalstay, name ='totalstay'),
    path('find/', views.find, name ='find'),
    path('popular/', views.popular, name ='popular'),    

    path('login/', views.login, name='login'),
    path('theme/', views.showTheme, name='theme'),
    path('<str:theme>/stay/', views.stayFilter, name='stay'),
    path('<str:name>/detail/', views.stayDetail, name='staydetail'),
>>>>>>> 26f4beea27c7167f6d41785eb695130952d1665e
]

Django/ojo/ojo/urls.py
from django.conf.urls import url
from django.urls import path, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('homepage/', include('homepage.urls')),
] 

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Django/ojo/homepage/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

class User_info(models.Model):
    userid = models.CharField(max_length=70, blank=False, default='')
    email = models.EmailField(max_length=200,blank=False, default='')
    passwd = models.CharField(max_length=70, blank=False, default='')

    def __str__(self) -> str:
        return self.userid

Django/ojo/homepage/forms.py
# from django.contrib.auth.models import User
# from django import forms

# class SignUpForm(forms.ModelForm):
#    # password = forms.CharField(lable='Password', widget=forms.PasswordInput)

#     class Meta:
#         model = User
#         # fiedls에는 해당 모델에 대해 입력 받을 필드들을 나열한다.
#         # + 추가 필드도 포함 될 수 있다.
#         fields = ['userid','passwd','emailid']

Django/ojo/homepage/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
import json
from os import name

from pymongo import MongoClient
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from homepage.models import User_info
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login
from django.contrib import auth

# from homepage.MongoDbManager import MongoDbManager
from datetime import datetime
import pandas as pd
from homepage.Api import Json, recommandation
from homepage.MongoDbManager import MongoDbManager_insta
from django.core.paginator import Paginator
#from .forms import SignUpForm

# 0 = '혼자만의 숙소' 2 = '데이트하기 좋은 숙소' 3 = '특별한 체험이 있는 숙소' 4 = '고즈넉한 숙소' 5 = '감각있는 숙소'
# 6 = '아름다운 풍경이 가득한 숙소' 7 = '놀기 좋은 숙소' 8 = '편안한 분위기의 숙소' 9 = '하늘과 바다가 가득한 숙소'


filter = {'zero' : '오롯이 나를 위해 보내는 하루' , 'two':'너와 나, 우리 둘만의 하루', 'three':'당신의 하루를 특별하게','four':'고즈넉한 사색의 공간','five':'우리들만의 파티 플레이스',\
    'six':'자연 그대로를 품다','seven':'자연에서의 놀이터','eight':'따듯하고 포근한 공간을 그리며','nine':'하늘과 바다가 가득 밀려드는'}
# Create your views here.
def home(requests):
    return render(requests, 'homepage/index.html')

def register(requests):
    return render(requests, 'homepage/register.html')

def regcon(requests):
    userid = requests.POST['userid']
    email = requests.POST['emailid']
    passwd = requests.POST['userpw']

    qs = User.objects.create_user(userid, email, passwd)
    qs.save()

    return HttpResponseRedirect(reverse('homepage:register'))

def logcon(requests):
    if requests.method == 'POST':
        userid = requests.POST['userid']
        passwd = requests.POST['userpw']
        result = authenticate(username = userid, password = passwd)
        user=User()


        if result is not None:
            # login(result)
            return HttpResponseRedirect(reverse('homepage:choice'))
        else:
            #return HttpResponseRedirect(reverse('homepage:relogin'))
            return render(requests, 'homepage/relogin.html')
            
def login(requests):
    return render(requests, 'homepage/login.html')

def choice(requests):
    return render(requests, 'homepage/choice.html')

def totalstay(requests):
    if requests.method == 'POST':
        return render(requests, 'homepage/find.html')

    all = Json.all_info()
    page = int(requests.GET.get('page',1))
    paginator = Paginator(all, 16)
    page_obj = paginator.get_page(page)
    context = {'question_list': page_obj}
    if requests.method == 'GET':
        return render(requests, 'homepage/totalstay.html', context)


global tmp_list 
def find(requests):
    global tmp_list 
    if requests.method == 'POST':
        print(requests.POST.get('tag'))
        print(requests.POST.get('local'))
        if requests.POST.get('tag') and requests.POST.get('local') != '0':
            tag = requests.POST.get('tag')
            local  = requests.POST.get('local')
            tot = Json.tag_local_find_name(tag, local)
            tmp_list = tot
            
        elif requests.POST.get('tag'):
            tag  = requests.POST.get('tag')
            tot = Json.tag_find_name(tag)
            tmp_list = tot
            
        elif requests.POST.get('local'):
            local  = requests.POST.get('local')
            tot = Json.local_find_name(local)
            tmp_list = tot

    page = int(requests.GET.get('page',1))
    paginator = Paginator(tmp_list, 16)
    page_obj = paginator.get_page(page)
    context = {'question_list': page_obj}
    return render(requests, 'homepage/find.html', context)


def popular(requests):
    if requests.method == 'GET':
        like = Json.most_like()
        page = int(requests.GET.get('page',1))
        paginator = Paginator(like, 16)
        page_obj = paginator.get_page(page)
        context = {'question_list': page_obj}
        return render(requests, 'homepage/popular.html', context)


def showTheme(requests):
    context = filter
    return render(requests, 'homepage/theme.html', context)

def stayFilter(requests, theme):
<<<<<<< HEAD
    # print(theme)
    # nowtime = datetime.today().strftime("%Y-%m-%d")
    # co_if = Json.corona_info(nowtime)
    # insta_if = Json.insta_info(theme)
    # co_if.update(insta_if)
    # co_if['filter'] = theme
    # print(co_if)
    return render(requests, 'homepage/stayfilter.html')

def stayDetail(requests, name):
    return render(requests, 'homepage/staydetail.html')
=======
    nowtime = datetime.today().strftime("%Y-%m-%d")

    if requests.method == 'GET':
        page = int(requests.GET.get('page',1))  # 페이지
        insta_if, _ = Json.insta_info(theme)
        co_if = Json.corona_info(nowtime)    
        paginator = Paginator(insta_if, 4)  # 페이지당 10개씩 보여주기
        page_obj = paginator.get_page(page)
        context = {'question_list': page_obj}
        context.update(co_if)
        context['filter'] = theme
        return render(requests, 'homepage/stayfilter.html', context)

    co_if = Json.corona_info(nowtime)
    _, insta_if = Json.insta_info(theme)
    co_if.update(insta_if)
    co_if['filter'] = theme
    return render(requests, 'homepage/stayfilter.html', co_if)

# def stayFilter(requests, theme):
#     nowtime = datetime.today().strftime("%Y-%m-%d")
#     co_if = Json.corona_info(nowtime)
#     insta_if = Json.insta_info(theme)
#     co_if.update(insta_if)
#     co_if['filter'] = theme
#     return render(requests, 'homepage/stayfilter.html', co_if)

def stayDetail(requests, name): 
    name_info = {}
    context = recommandation.insta_REC(name)
    context['b10'] = name
    output = Json.name_info(context)
    return render(requests, 'homepage/staydetail.html', output)

>>>>>>> 26f4beea27c7167f6d41785eb695130952d1665e

   

Django/ojo/homepage/templates/homepage/choice.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>OJO - SNS기반의 감성숙소 추천</title>
        <link rel="icon" type="image/x-icon" href="{% static 'assets/ojo_favi.ico' %}" />

        <!-- <link rel="icon" type="image/x-icon" href="../static/assets/ojo_favi.ico" /> -->
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.15.3/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Varela+Round" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        {% load static %}
        <link href="{% static 'css/choice.css' %}" rel="stylesheet" />
        
        <link href="https://fonts.googleapis.com/css2?family=Black+Han+Sans&display=swap" rel="stylesheet">

        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Do+Hyeon&family=Gowun+Batang&family=Nanum+Myeongjo&display=swap" rel="stylesheet">

    </head>
    <body id="page-top">
        <!-- Contact-->
        <section class="py-5">
            <div class="container px-9 px-lg-10 ">
                <div class="col-md-10 col-lg-8 mx-auto text-center">
                    <!-- <i class="far fa-paper-plane fa-2x mb-2 text-white"></i> -->
                    <h2 class="font-NM" style="font-size: 40px;">모든 순간이 여행이 되도록</h2><br/><br/><br/>
                </div>
                <div class="row gx-8 gx-lg-9 row-cols-2 row-cols-md-4 row-cols-xl-3 justify-content-center">

                    <div class="col mb-5">
                        <div class="card h-100">
                            <!-- Sale badge-->
                            <!-- <div class="badge bg-dark text-white position-absolute" style="top: 0.5rem; right: 0.5rem">Sale</div> -->
                            <!-- Product image-->
                            <img class="card-img-top" src="{% static 'img/22.jpg' %}" alt="..." style="
                            width: 414px;
                            height: 300px;
                        "/>
                            <!-- Product details-->
                            <div class="card-body p-4">
                                <div class="text-center">
                                    
                                    <a class="btn btn-outline-dark mt-auto" href="{% url 'homepage:theme' %}"><h5 class = "font-GB" style="font-size: 17px;">테마별 숙소<br/> 보러가기</h5></a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col mb-5">
                        <div class="card h-300">
                            <!-- Sale badge-->
                            <!-- <div class="badge bg-dark text-white position-absolute" style="top: 0.5rem; right: 0.5rem">Sale</div> -->
                            <!-- Product image-->
                            <img class="card-img-top" src="{% static 'img/24.jpg' %}" alt="..." style="
                            width: 414px;
                            height: 300px;
                        " />
                            <!-- Product details-->
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <!-- Product name-->
                                    <a class="btn btn-outline-dark mt-auto" href="{% url 'homepage:popular' %}"><h5 class = "font-GB" style="font-size: 17px;">인기숙소<br/> 보러가기</h5></a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col mb-5">
                        <div class="card h-300">
                            <!-- Product image-->
                            <img class="card-img-top" src="{% static 'img/23.png' %}" alt="..." style="
                            width: 414px;
                            height: 300px;
                        "/>
                            <!-- Product details-->
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <!-- Product name-->
                                    <a class="btn btn-outline-dark mt-auto" href="{% url 'homepage:totalstay' %}"><h5 class = "font-GB" style="font-size: 17px;">전체숙소<br/> 보러가기</h5></a>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- Footer-->
        <footer class="footer bg-black small text-center text-white-50"><div class="container px-4 px-lg-5">Copyright &copy; OJO 2021 2021.10.08 v1.0.0</div></footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        {% load static %}
        <script src="{% static 'js/scripts.js' %}"></script>
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <!-- * *                               SB Forms JS                               * *-->
        <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
    </body>
</html>

Django/ojo/homepage/templates/homepage/find.html
{% load static %}
{% load dict_filter %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>OJO - SNS기반의 감성숙소 추천</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'assets/ojo_favi.ico' %}" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href='{% static "css/stay_styles.css" %}' rel="stylesheet" />

        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Black+Han+Sans&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css2?family=Do+Hyeon&family=Gowun+Batang&family=Gowun+Dodum&family=Nanum+Myeongjo&display=swap" rel="stylesheet">
    </head>
    <body>
        <!-- Responsive navbar-->
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container px-4 px-lg-5" style="font-family: 'Gowun Dodum', serif;">
                <a class="font-GB" href="{% url 'homepage:choice' %}" style="text-decoration: none;">OJO 감성숙소</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="/homepage/theme">테마 선택하기</a></li>
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="/homepage/popular">인기 숙소 둘러보기</a></li>
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="/homepage/totalstay">전체 숙소 둘러보기</a></li>
                    </ul>
                    <form class="d-flex">
                        <button class="btn btn-outline-dark" href="http://ncov.mohw.go.kr/socdisBoardView.do?brdId=6&amp;brdGubun=1">
                            <a class="btn btn-outline-dark" href="http://ncov.mohw.go.kr/">코로나 안전정보</a>
                            <span class="badge bg-dark text-white ms-1 rounded-pill"></span>
                        </button>
                    </form>
                </div>
            </div>
        </nav>
        <!-- Page header with logo and tagline-->
        <header class="py-5 bg-white border-bottom mb-4"  style='background-image:url(../img/1.jpg)'>
            <div class="container">
                <div class="text-center my-5">
                    <h1 class="font-GB" style="font-size: 40px;">전체숙소</h1>
                    <p class="font-GD" style="font-size: 30ps;"> 감성숙소 리스트</p>
                </div>
            </div>
        </header>
        <!-- Page content-->
        <div class="container">
            <!-- <div class="row"> -->

                <!-- <div class="card-header"> 태그를 이용해서 검색하세요 </div> -->
                    <!-- <div class="card-body" style="padding: 50px;">
                        <div class="input-group">
                            <form method="POST" action="{% url 'homepage:find' %}" class="nav-link dropdown-toggle" style="margin-left: 7%; margin-top: 5%;">
                                {% csrf_token %}
                                <select name="local" id="id_local">
                                    <option value="0" selected>지역 선택</option>
                                    <option value="서울">서울</option>
                                    <option value="부산">부산</option>
                                    <option value="제주">제주</option>
                                    <option value="강원">강원</option>
                                    <option value="인천">인천</option>
                                    <option value="경기">경기</option>
                                    <option value="대구">대구</option>
                                    <option value="광주">광주</option>
                                    <option value="대전">대전</option>
                                    <option value="울산">울산</option>
                                    <option value="세종">세종</option>
                                    <option value="경남">경남</option>
                                    <option value="경북">경북</option>
                                    <option value="전남">전남</option>
                                    <option value="전북">전북</option>
                                    <option value="충북">충북</option>
                                    <option value="충남">충남</option>
                                </select>
                            
              
                                <input class="form-control" name="tag" type="text" placeholder="태그를 이용해서 검색하세요..." aria-label="Enter search term..." aria-describedby="button-search" />
                                <button class="btn btn-primary" id="button-search"  type="submit">SEARCH</button>
                                # 바다, # 한옥, # 힐링, # 수영장,# 마을, # 오션뷰, # 바베큐, # 풍경, # 독채, # 스파, # 자쿠지, # 돌담
                            </form>

                        </div>
                    </div>
                </div> -->
                
                
                <!-- Nested row for non-featured blog posts-->
            <div class="row">
            {% for list in question_list %}
                <div class="col-lg-3">
                    <!-- Blog post-->
                    <div class="card mb-4">
                        {% if list %}
                        <a href="{% url 'homepage:staydetail' list.name %}"><img class="card-img-top" src="{% get_static_prefix %}img/{{ list.img }}.jpg"alt="..." style="width: 306px; height: 306px;" /></a>
                        <div class="card-body">
                            <!-- <div class="small text-muted">January 1, 2021</div> -->
                            <a href="{% url 'homepage:staydetail' list.name %}"><h2 class="card-title h4">{{ list | get_dict:'name' }}</h2></a>
                            <p class="card-text" style="font-size: 10px; height: 100px;">{{ list | get_dict:'tags' }} <br/></p>
                            <!-- <a class="btn btn-primary" href="{% url 'homepage:staydetail' list.name %}">숙소상세</a> -->
                        </div>
                        {% endif %}
                    </div>
                </div>
            {% endfor %}
            </div>

            <!-- Pagination-->
            <nav aria-label="Pagination">
                <hr class="my-0" />
                <ul class="pagination justify-content-center my-4">
                    {% if question_list.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href=>이전</a>
                    </li>
                    {% else %}
                    <li class="page-item disabled">
                        <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
                    </li>
                    {% endif %}
                    <!-- 페이지리스트 -->
                    {% for page_number in question_list.paginator.page_range %}
                        {% if page_number == question_list.number %}
                        <li class="page-item active" aria-current="page">
                            <a class="page-link" type="submit" href="?page={{ page_number }}">{{ page_number }}</a>
                        </li>
                        {% else %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
                        </li>
                        {% endif %}
                    {% endfor %}
                    <!-- 다음페이지 -->
                    {% if question_list.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_number }}">다음</a>
                    </li>
                    {% else %}
                    <li class="page-item disabled">
                        <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
                    </li>
                    {% endif %}
                </ul>
            </nav>
                        
            </div>
        </div>

        
        <!-- Footer-->
        <footer class="py-5 bg-dark">
            <div class="container"><p class="m-0 text-center text-white">Copyright &copy; OJO 2021</p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src='{% static "js/stay_scripts.js" %}'></script>
    </body>
</html>

Django/ojo/homepage/templates/homepage/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>OJO - SNS기반의 감성숙소 추천</title>
        <link rel="icon" type="image/x-icon" href="{% static 'assets/ojo_favi.ico' %}" />

        <!-- <link rel="icon" type="image/x-icon" href="../static/assets/ojo_favi.ico" /> -->
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.15.3/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Varela+Round" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        {% load static %}
        <link href="{% static 'css/login.css' %}" rel="stylesheet" />

        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Black+Han+Sans&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css2?family=Do+Hyeon&family=Gowun+Batang&family=Gowun+Dodum&family=Nanum+Myeongjo&display=swap" rel="stylesheet">

    </head>
    <body id="page-top">
        <!-- Signup-->
        
        <section class="signup-section">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5">
                    <div class="col-md-10 col-lg-8 mx-auto text-center">
                        <!-- <i class="far fa-paper-plane fa-2x mb-2 text-white"></i> -->
                        <h2 class="font-GD" style="font-size: 30px;">OJO SIGN IN</h2>
                        <!-- <h2 class="text-white">OJO SIGN IN</h2> -->
                        <!-- * * * * * * * * * * * * * * *-->
                        <!-- * * SB Forms Contact Form * *-->
                        <!-- * * * * * * * * * * * * * * *-->
                        <!-- This form is pre-integrated with SB Forms.-->
                        <!-- To make this form functional, sign up at-->
                        <!-- https://startbootstrap.com/solution/contact-forms-->
                        <!-- to get an API token!-->
                        <form class="form-signup" id="contactForm" action="{% url 'homepage:logcon'%}" method='POST'>
                            {% csrf_token %}
                            <!-- Email address input-->
                            <!-- <div class="row input-group-newsletter"> -->
                                <div class="col_id">
                                    <input class="form-control" name="userid" type="text" placeholder="Enter ID..." aria-label="Enter ID..." data-sb-validations="required,text" />
                                    <br>
                                </div> 
                            
                                <div class="col_pw">
                                    <input class="form-control" name="userpw" type="password" placeholder="Enter password..." aria-label="Enter password..." data-sb-validations="required,password" />
                                    <br>
                                </div>
                                

                                <div class="col-auto"> 
                                    <a class="btn btn-primary" href="/homepage/register"style="
                                    font-family: 'Gowun Dodum';
                                ">회원가입</a> 
                                    <button class="btn btn-primary " name="submitButton" type="submit" style="
                                    font-family: 'Gowun Dodum';
                                ">로그인</button>
                                    <!-- <button class="btn btn-primary " id="submitButton" type="submit" >Notify Me!</button> -->
                                </div>
                            <!-- </div> -->
                            <div class="invalid-feedback mt-2" data-sb-feedback="emailAddress:required">An email is required.</div>
                            <div class="invalid-feedback mt-2" data-sb-feedback="emailAddress:email">Email is not valid.</div>
                            <!-- Submit success message-->
                            <!---->
                            <!-- This is what your users will see when the form-->
                            <!-- has successfully submitted-->
                            <div class="d-none" id="submitSuccessMessage">
                                <div class="text-center mb-3 mt-2 text-white">
                                    <div class="fw-bolder">Form submission successful!</div>
                                    To activate this form, sign up at
                                    <br />
                                    <a href="https://startbootstrap.com/solution/contact-forms">https://startbootstrap.com/solution/contact-forms</a>
                                </div>
                            </div>
                            <!-- Submit error message-->
                            <!---->
                            <!-- This is what your users will see when there is-->
                            <!-- an error submitting the form-->
                            <div class="d-none" id="submitErrorMessage"><div class="text-center text-danger mb-3 mt-2">Error sending message!</div></div>
                        </form>
                    </div>
                </div>
            </div>
        </section>       
      
        <!-- Footer-->
        <footer class="footer bg-black small text-center text-white-50"><div class="container px-4 px-lg-5">Copyright &copy; OJO 2021</div></footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        {% load static %}
        <script src="{% static 'js/scripts.js' %}"></script>
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <!-- * *                               SB Forms JS                               * *-->
        <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
        </section>
    </body>
</html>